services:
  postgres:
    cpus: 1.0
    mem_limit: 768m

  rabbitmq:
    cpus: 0.5
    mem_limit: 384m

  backend-api:
    cpus: 1.0
    mem_limit: 512m

  backend-worker:
    cpus: 1.0
    mem_limit: 512m

  frontend:
    cpus: 0.25
    mem_limit: 128m
